name: agentteams-export-metadata

on:
  workflow_dispatch:

jobs:
  export-and-open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
      - name: Build intake metadata
        env:
          PROJECT_ID: ${{ vars.AGENTTEAMS_PROJECT_ID }}
          REPO_NAME: ${{ github.repository }}
        run: |
          python - <<'PY'
          from __future__ import annotations
          from datetime import datetime, timezone
          from pathlib import Path
          import yaml

          project_id = (Path(".").resolve().name).lower().replace("_", "-")
          env_project = Path(".github").joinpath("..")  # no-op to avoid lint warning
          import os
          project_id = os.environ.get("PROJECT_ID", project_id).strip() or project_id
          repo_name = os.environ.get("REPO_NAME", "").strip()

          tasks_dir = Path(".takt/tasks")
          counts = {"todo": 0, "in_progress": 0, "in_review": 0, "blocked": 0, "done": 0}
          blocked_ratio = 0.0
          if tasks_dir.exists():
            files = sorted(tasks_dir.glob("TASK-*.yaml"))
            for file in files:
              data = yaml.safe_load(file.read_text(encoding="utf-8")) or {}
              status = str(data.get("status") or "").strip()
              if status in counts:
                counts[status] += 1
            total = sum(counts.values())
            blocked_ratio = (counts["blocked"] / total) if total else 0.0

          captured_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
          intake = {
            "project_id": project_id,
            "repo": f"github.com/{repo_name}",
            "captured_at": captured_at,
            "window_days": 14,
            "task_counts": counts,
            "lead_time_p50_hours": 0.0,
            "queue_p95_hours": 0.0,
            "rework_rate": 0.0,
            "blocked_ratio": round(blocked_ratio, 4),
            "incident_fingerprints": [],
            "policy_failures": [],
            "top_overlaps": [],
          }

          out = Path("agentteams-intake.yaml")
          out.write_text(yaml.safe_dump(intake, allow_unicode=True, sort_keys=False), encoding="utf-8")
          print(f"generated intake: {out}")
          PY
      - name: Push intake PR to central AgentTeams repo
        env:
          HUB_REPO: ${{ vars.AGENTTEAMS_HUB_REPO }}
          PROJECT_ID: ${{ vars.AGENTTEAMS_PROJECT_ID }}
          BOT_TOKEN: ${{ secrets.AGENTTEAMS_BOT_TOKEN }}
        run: |
          if [ -z "${HUB_REPO}" ] || [ -z "${PROJECT_ID}" ] || [ -z "${BOT_TOKEN}" ]; then
            echo "Missing required vars/secrets: AGENTTEAMS_HUB_REPO, AGENTTEAMS_PROJECT_ID, AGENTTEAMS_BOT_TOKEN"
            exit 1
          fi

          stamp="$(date -u +%Y%m%dT%H%M%SZ)"
          branch="bot/intake-${PROJECT_ID}-${stamp}"
          target_file=".takt/control-plane/intake/${PROJECT_ID}/${stamp}.yaml"

          git clone "https://x-access-token:${BOT_TOKEN}@github.com/${HUB_REPO}.git" hub-repo
          cd hub-repo
          git checkout -b "${branch}"
          mkdir -p "$(dirname "${target_file}")"
          cp ../agentteams-intake.yaml "${target_file}"

          git config user.name "agentteams-bot"
          git config user.email "agentteams-bot@users.noreply.github.com"
          git add "${target_file}"
          git commit -m "chore(intake): ${PROJECT_ID} metadata ${stamp}"
          git push origin "${branch}"

          export GH_TOKEN="${BOT_TOKEN}"
          gh pr create \
            --repo "${HUB_REPO}" \
            --base main \
            --head "${branch}" \
            --title "chore(intake): ${PROJECT_ID} metadata ${stamp}" \
            --body "Automated metadata-only intake PR from ${GITHUB_REPOSITORY}. This PR should modify only intake paths."
